-- Seed task templates and steps from tasks.json
-- This file is auto-generated by scripts/generate-seed-sql.js
-- DO NOT EDIT MANUALLY - regenerate using: node scripts/generate-seed-sql.js
--
-- This seed file uses ON CONFLICT DO NOTHING to make it idempotent
-- You can run this multiple times without creating duplicates
-- Tasks are ordered by dependencies (tasks without dependsOn first)

-- Insert task templates (idempotent - will skip if template already exists)
INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  'Request Multiple Certified Copies of the Death Certificate',
  'Obtain multiple certified copies—typically 10‑15—of the death certificate through the funeral home or county vital‑records office.',
  'immediately'::task_phase,
  'Within 24‑48 hours of death',
  'high'::task_priority,
  true,
  ARRAY['In-Person'::contact_method, 'Online'::contact_method, 'Mail'::contact_method, 'Phone'::contact_method],
  ARRAY['Government‑issued photo ID', 'Proof of relationship (marriage certificate or birth certificate)', 'Payment for certificate fees (varies by state; usually $10–25 each)'],
  'Almost every other administrative task—insurance claims, Social Security, bank account changes—requires a certified copy. Ordering enough at once prevents costly delays.',
  'Funeral directors can usually submit the request on your behalf; ask them first. Order a few extras—replacing them later can take weeks.',
  'Funeral home director or county vital‑records office clerk',
  'Search ''[Your County] vital records office'' online or ask the funeral director for direct numbers and forms.',
  'A short form, payment, and a 1‑3 business‑day processing period. Some counties let you pay online and ship by overnight mail.',
  'Funeral director, estate attorney (if questions about who is authorized)',
  'You receive 10‑15 sealed, certified copies ready to distribute to institutions.',
  'Order 10–15 certified copies up front.',
  'Signed authorization letter plus your ID copy if a friend or professional files the request for you.',
  ARRAY['CDC Vital Records Office Finder'],
  ARRAY['death-certificate-request-template.pdf'],
  'Store originals in a fireproof envelope; send only certified copies by mail—never the original.',
  ARRAY['9abac705-d2d1-4489-bbea-1ba2cf7b0528'::uuid, 'c64b4ac9-ca2e-4e0d-88ec-4da5b33d1dc9'::uuid]::uuid[],
  true,
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  '574e2267-6f4c-4cf9-a1e7-6612e77797c1'::uuid,
  'Pay Immediate Household Bills and Enable Auto‑Pay',
  'Prevent missed or late payments by covering essential household bills and turning on auto‑pay where available.',
  'first-month'::task_phase,
  'Within first 2 weeks',
  'medium'::task_priority,
  true,
  ARRAY['Online'::contact_method, 'Phone'::contact_method],
  ARRAY['Latest statements', 'Bank account or credit‑card details for auto‑pay setup'],
  'Avoid late fees, credit damage, or service shut‑offs while you focus on larger estate matters.',
  'Freeze any non‑essential spending until you have a complete financial picture.',
  'Each service provider''s billing department',
  'Log in to online portals, check paper statements, or call customer‑service numbers on statements.',
  'Most companies can flip auto‑pay on immediately once an online profile is verified.',
  NULL,
  'All critical bills marked paid and set to auto‑pay for at least the next 60 days.',
  NULL,
  'Online log‑in credentials or a notarized letter granting authorization.',
  NULL,
  NULL,
  'Create a shared spreadsheet of due dates so helpers know what''s covered.',
  ARRAY['2706d589-2d28-4f1e-9ea4-d937bddab3a9'::uuid, '28d2819d-25e0-4d80-9b1f-074d2888e2ec'::uuid]::uuid[],
  false,
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  '2706d589-2d28-4f1e-9ea4-d937bddab3a9'::uuid,
  'Cancel Non‑Essential Subscriptions and Memberships',
  'Stop recurring charges for services the deceased no longer needs (streaming, gym, magazines, apps).',
  'first-month'::task_phase,
  'Within first 30 days',
  'low'::task_priority,
  true,
  ARRAY['Online'::contact_method, 'Email'::contact_method, 'Phone'::contact_method],
  ARRAY['Login credentials or last billing statement'],
  'Reduces monthly spend and simplifies financial tracking.',
  'Search email inboxes for the word ''receipt'' to find hidden subscriptions.',
  'Each subscription''s customer‑service team or online cancellation form',
  'Log in to Apple/Google subscriptions, bank statements, or use a subscription‑tracker app.',
  'Most digital services cancel immediately; some gyms require written notice.',
  NULL,
  'Confirmation emails show zero future billing dates.',
  NULL,
  'List of services + logins (or power of attorney if required).',
  ARRAY['Truebill/RocketMoney Subscription Tracker'],
  NULL,
  'Ask banks for a 12‑month transaction history to spot annual renewals.',
  ARRAY['574e2267-6f4c-4cf9-a1e7-6612e77797c1'::uuid]::uuid[],
  false,
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  'dd5a79f0-459e-4507-a95e-1d1581e6809f'::uuid,
  'Identify a New Emergency Contact',
  'Designate a new primary emergency contact on medical, school, and work records if the deceased previously filled that role.',
  'first-month'::task_phase,
  'Within first 30 days',
  'low'::task_priority,
  false,
  ARRAY['Online'::contact_method, 'Email'::contact_method, 'In-Person'::contact_method],
  ARRAY['Photo ID', 'Relationship documentation (if required)'],
  'Ensures someone can be reached quickly in an emergency.',
  'Choose someone nearby who answers calls reliably and knows key medical details.',
  'Schools, doctors, employers, and any organization that lists an emergency contact.',
  'Log in to each institution''s portal or call the front desk.',
  'Typically a simple form or online field change; must be signed or initialed.',
  NULL,
  'All records list the new emergency contact and confirm receipt.',
  NULL,
  NULL,
  NULL,
  NULL,
  'Keep a digital note with all emergency contacts and share with close family.',
  NULL,
  false,
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  '28d2819d-25e0-4d80-9b1f-074d2888e2ec'::uuid,
  'Transfer Technology and Utility Accounts',
  'Update or transfer accounts such as internet, phone, electricity, streaming, security systems, password managers, photo clouds, and crypto wallets.',
  'first-month'::task_phase,
  'Within 30 days',
  'medium'::task_priority,
  true,
  ARRAY['Phone'::contact_method, 'Email'::contact_method, 'Online'::contact_method],
  ARRAY['Death certificate (certified copy)', 'Account numbers or login credentials', 'Letter of authorization if delegating'],
  'Prevents service interruptions and avoids accidental data or asset loss.',
  'Create a master list of every service and cross them off as you confirm the transfer.',
  'Customer‑service/billing department of each provider.',
  'Look up numbers on recent bills or the provider''s official website; avoid numbers from email/spam.',
  'Most transfers are immediate after verification; crypto may require additional security steps.',
  'Tech‑savvy family member or IT consultant for complex setups.',
  'All services either canceled or re‑registered under the surviving spouse''s name with uninterrupted access.',
  NULL,
  'Written authorization and certified copy of death certificate.',
  NULL,
  NULL,
  'Don''t delete password‑manager accounts; export passwords first.',
  ARRAY['c47e4b7a-8072-4c1f-8817-f727c3c0d51e'::uuid]::uuid[],
  false,
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  '34379d19-9e35-446c-88bb-686f23389dd3'::uuid,
  'Schedule Social Security Appointments',
  'Set up in‑person appointments with the Social Security Administration (SSA) for survivor and dependent benefits.',
  'first-month'::task_phase,
  'Within 30 days',
  'high'::task_priority,
  true,
  ARRAY['Phone'::contact_method],
  ARRAY['Death certificate (certified copy)', 'Marriage certificate (for spousal benefits)', 'Birth certificates of dependent children'],
  'Secures ongoing income for survivors and avoids benefit overpayments that must be repaid.',
  'Call early in the morning for shorter hold times.',
  'Social Security Administration 1‑800‑772‑1213',
  'Use ssa.gov/locator to confirm your local office and schedule options.',
  'A phone agent will schedule an in-office visit; wait times for appointments can be 1-2 weeks.',
  'Social Security disability attorney (if complex benefit questions)',
  'Appointment date confirmed and written on your calendar.',
  NULL,
  'Only scheduling can be delegated; survivor must attend in person.',
  ARRAY['SSA Survivor Benefits FAQ'],
  NULL,
  'Ask the agent to list every document you''ll need—bringing extras prevents repeat visits.',
  ARRAY['c64b4ac9-ca2e-4e0d-88ec-4da5b33d1dc9'::uuid]::uuid[],
  false,
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  '9abac705-d2d1-4489-bbea-1ba2cf7b0528'::uuid,
  'File Death Claim with Life Insurance Company',
  'Submit claim forms and required documents to the insurer to receive the policy payout.',
  'immediately'::task_phase,
  'Within first week',
  'high'::task_priority,
  false,
  ARRAY['Phone'::contact_method, 'Email'::contact_method, 'Mail'::contact_method],
  ARRAY['Death certificate (certified copy)', 'Policy number', 'Government ID of beneficiary', 'Completed claim form'],
  'Provides critical funds for funeral costs, debts, and living expenses.',
  'Insurers generally accept certified copies—don''t mail your only original.',
  'Insurer''s claims department (number on policy docs)',
  'Call agent of record or visit insurer''s website for claims portal.',
  'Claims rep verifies documents and issues payout within 2-4 weeks.',
  'Insurance agent or financial advisor',
  'Payout deposited or check received; policy marked closed.',
  NULL,
  'Beneficiary must sign claim form (wet or e‑signature).',
  NULL,
  ARRAY['life-insurance-claim-checklist.pdf'],
  'Keep a copy of every form you submit; note date/time of all calls.',
  ARRAY['f12d0c64-9c3e-44c3-9b3e-51e5b2f4e7b1'::uuid, 'e9e8956c-a06c-4370-af18-d4deec6e2f35'::uuid]::uuid[],
  false,
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  '0cd648d6-864f-4b97-b5fc-e9c14d085059'::uuid,
  'Contact Employer Regarding Benefits',
  'Notify employer, request final paycheck, review life insurance through work, and inquire about COBRA or retirement benefits.',
  'first-month'::task_phase,
  'Within 2 weeks',
  'medium'::task_priority,
  true,
  ARRAY['Phone'::contact_method, 'Email'::contact_method],
  ARRAY['Death certificate (certified copy)', 'Employee ID or personnel info'],
  'Secures final wages and uncovers any company‑sponsored life insurance or pension.',
  'Ask HR if the company offers free grief counseling or legal aid—the benefit list is often buried.',
  'HR department or direct supervisor',
  'Call main company number; request HR. Or email HR@company.com (common convention).',
  'HR will initiate payroll and benefit termination; you may receive forms by email.',
  'Employment attorney (if disputes)',
  'Final pay, benefits outline, COBRA packet received.',
  NULL,
  'Authorization letter and death certificate copy.',
  NULL,
  NULL,
  'Ask specifically about group life insurance—many families miss this payout.',
  ARRAY['9abac705-d2d1-4489-bbea-1ba2cf7b0528'::uuid]::uuid[],
  false,
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  'c64b4ac9-ca2e-4e0d-88ec-4da5b33d1dc9'::uuid,
  'Notify Social Security Administration',
  'Report the death and apply in person for survivor and dependent benefits.',
  'first-month'::task_phase,
  'Within 30 days (often same day as appointment)',
  'high'::task_priority,
  false,
  ARRAY['In-Person'::contact_method],
  ARRAY['Death certificate (certified copy)', 'Marriage certificate', 'Birth certificates of dependent children', 'IDs and Social Security numbers for all applicants'],
  'Stops overpayments and starts monthly survivor income.',
  'Bring spare certified copies in case another department needs one.',
  'Local Social Security field office',
  'Use SSA office locator (ssa.gov/locator) or number given when appointment was scheduled.',
  'An agent will review documents, input data, and confirm benefits start dates.',
  'Social Security attorney (only if claim complexity arises)',
  'Survivor and/or dependent benefits approved and scheduled.',
  NULL,
  NULL,
  ARRAY['SSA Survivor Benefits Checklist'],
  NULL,
  'Ask for a receipt showing your benefits claim was filed—this speeds problem resolution.',
  ARRAY['34379d19-9e35-446c-88bb-686f23389dd3'::uuid]::uuid[],
  false,
  '34379d19-9e35-446c-88bb-686f23389dd3'::uuid,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  'f12d0c64-9c3e-44c3-9b3e-51e5b2f4e7b1'::uuid,
  'Update Insurance Information (Health, Auto, Home, Umbrella)',
  'Remove the deceased from all active insurance policies, add surviving spouse or executor as primary, and confirm new premiums.',
  'first-month'::task_phase,
  'Within 30 days',
  'medium'::task_priority,
  true,
  ARRAY['Phone'::contact_method, 'Email'::contact_method, 'Online'::contact_method],
  ARRAY['Death certificate (certified copy)', 'Policy numbers', 'Driver''s license or other government ID'],
  'Prevents mistaken billing and ensures you''re properly covered at the correct rate.',
  'Ask if there''s a prorated refund for unused premiums on the deceased''s portion.',
  'Each insurer''s customer-service or agent of record',
  'Policy paperwork, insurer website, or agent business card.',
  'CSR will verify identity, request the death certificate, and email confirmation of changes.',
  'Independent insurance broker (for rate shopping)',
  'All policies list the correct named insured and new premiums take effect.',
  NULL,
  'Letter of authorization plus certificate copy.',
  NULL,
  NULL,
  'Combine auto & home on one carrier to save 10–15% once names are updated.',
  ARRAY['9abac705-d2d1-4489-bbea-1ba2cf7b0528'::uuid]::uuid[],
  false,
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  'd8800e24-2fb7-46e6-9df0-d99162da7a8d'::uuid,
  'Claim 401(k) Plan',
  'Initiate rollover or direct payout of the deceased''s employer-sponsored 401(k).',
  'months-2-3'::task_phase,
  'Within 90 days',
  'medium'::task_priority,
  false,
  ARRAY['Phone'::contact_method, 'Mail'::contact_method, 'Online'::contact_method],
  ARRAY['Death certificate (certified copy)', '401(k) plan beneficiary form', 'Rollover IRA account details (if applicable)'],
  'Delays can trigger required minimum distributions and tax penalties.',
  'Rolling to an inherited IRA often preserves tax advantages—consult a fiduciary first.',
  'Plan administrator or HR benefits center',
  'Statement footer, employer HR, or Vanguard/Fidelity call center depending on custodian.',
  'Forms packet, choice of lump-sum or rollover, 2-4 week processing.',
  'Fiduciary financial advisor, CPA',
  'Assets transferred into the survivor''s inherited IRA or paid out as elected.',
  NULL,
  'Beneficiary must sign; POA generally not accepted after death.',
  ARRAY['IRS Publication 590-B'],
  ARRAY['inherited-ira-flowchart.pdf'],
  'Check for after-tax (Roth) sub-accounts; they follow different rules.',
  ARRAY['0cd648d6-864f-4b97-b5fc-e9c14d085059'::uuid, 'e9e8956c-a06c-4370-af18-d4deec6e2f35'::uuid]::uuid[],
  false,
  '0cd648d6-864f-4b97-b5fc-e9c14d085059'::uuid,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  '0ffe71e3-6354-4967-8879-09786e41cde3'::uuid,
  'Contact Pension Plan Administrator',
  'Claim any pension benefits or survivor annuity the deceased earned.',
  'months-2-3'::task_phase,
  'Within 3 months',
  'medium'::task_priority,
  false,
  ARRAY['Phone'::contact_method, 'Mail'::contact_method],
  ARRAY['Death certificate (certified copy)', 'Marriage certificate (if spousal survivor benefit)', 'Pension plan statement'],
  'Pension income may replace part of the lost salary and may be forfeited if claims aren''t timely.',
  'Some pensions allow retroactive lump-sum of missed payments if filed within a year; ask specifically.',
  'Pension plan administrator (number on annual benefit statement)',
  'HR benefits center or National Registry of Unclaimed Retirement Benefits.',
  'Paper forms, proof of identity, optional direct-deposit setup.',
  'Pension consultant, CPA',
  'Monthly survivor payments begin or lump-sum benefit received.',
  NULL,
  NULL,
  NULL,
  NULL,
  'If you can''t locate the plan, file Form PBGC-100 to search the Pension Benefit Guaranty Corporation.',
  ARRAY['d8800e24-2fb7-46e6-9df0-d99162da7a8d'::uuid]::uuid[],
  false,
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  '323b80d8-3fbe-4c3b-a765-795a2b7b823e'::uuid,
  'Execute and Update Will and Estate Plan',
  'Meet with estate attorney to file will with probate court (if required) and execute any updates for the surviving spouse.',
  'months-2-3'::task_phase,
  'Within 90 days',
  'high'::task_priority,
  false,
  ARRAY['In-Person'::contact_method, 'Phone'::contact_method, 'Email'::contact_method],
  ARRAY['Original will', 'Death certificate (certified copy)', 'List of heirs and assets'],
  'Formally transfers property titles and grants executor authority to complete the estate.',
  'Bring a list of questions—lawyer meetings bill by the hour.',
  'Estate attorney',
  'State bar referral service or recommendations from financial advisor.',
  'Attorney will review documents, outline probate steps, and draft any needed updates.',
  'Estate attorney (mandatory), notary',
  'Court accepts will, letters testamentary issued, and updated documents signed.',
  NULL,
  NULL,
  NULL,
  NULL,
  'Record the meeting to capture instructions (ask permission).',
  ARRAY['4dce1e1f-16f1-4049-9047-14a8e52f1bb0'::uuid]::uuid[],
  true,
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  '4dce1e1f-16f1-4049-9047-14a8e52f1bb0'::uuid,
  'Administer Trust or Initiate Probate Proceedings',
  'If a revocable trust exists, begin trust administration; if not, open probate with the local court.',
  'months-2-3'::task_phase,
  '90-120 days',
  'high'::task_priority,
  false,
  ARRAY['In-Person'::contact_method, 'Online'::contact_method],
  ARRAY['Certified death certificate', 'Trust document or will', 'Asset inventory'],
  'Legally transfers ownership of titled assets and protects the estate from claims.',
  'Probate timelines vary by county—ask the clerk for typical duration.',
  'Estate attorney or probate court clerk',
  'Search ''[County] probate court'' or ask your attorney.',
  'Court hearings, notices to creditors, and formal accounting; 6-12 months typical.',
  'Estate attorney, CPA',
  'Court issues final order or trust distributes assets per terms.',
  NULL,
  NULL,
  NULL,
  ARRAY['probate-checklist.pdf'],
  'Keep a dedicated estate checking account for all disbursements and reimbursements.',
  ARRAY['323b80d8-3fbe-4c3b-a765-795a2b7b823e'::uuid]::uuid[],
  true,
  '323b80d8-3fbe-4c3b-a765-795a2b7b823e'::uuid,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  'b92ed511-6d9e-4845-927c-cdb1c6bfb795'::uuid,
  'File Estate Tax Return (Form 706)',
  'Prepare and submit the federal estate-tax return if the estate exceeds the IRS exemption limit.',
  'months-3-6'::task_phase,
  'Due 9 months after date of death',
  'medium'::task_priority,
  false,
  ARRAY['In-Person'::contact_method, 'Mail'::contact_method],
  ARRAY['Certified death certificate', 'Completed Form 706', 'Supporting asset valuations'],
  'Avoids IRS penalties and allows portability election for the surviving spouse.',
  'Even if below the limit, filing may preserve portability—consult your CPA.',
  'CPA or estate attorney',
  'Referrals or AICPA directory.',
  'Extensive schedules; possible IRS review 6-12 months later.',
  'CPA specializing in estates',
  'IRS acceptance letter or proof of filing.',
  NULL,
  NULL,
  ARRAY['Form 706 Instructions'],
  NULL,
  'Request a 6-month extension with Form 4768 if documents aren''t ready.',
  ARRAY[]::uuid[],
  false,
  '4dce1e1f-16f1-4049-9047-14a8e52f1bb0'::uuid,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  'caaaf141-fc72-4539-a5d8-9b2bd1d825e7'::uuid,
  'Begin Collecting Date-of-Death Account Statements',
  'Request bank, brokerage, and retirement account statements showing balances on the date of death.',
  'months-2-3'::task_phase,
  'Within 60 days',
  'high'::task_priority,
  true,
  ARRAY['Phone'::contact_method, 'Online'::contact_method, 'Mail'::contact_method],
  ARRAY['Certified death certificate', 'Executor''s letters testamentary or trust certificate'],
  'Needed for estate inventory, cost basis adjustment, and tax returns.',
  'Ask for PDF statements stamped ''Date of Death''—saves CPA time.',
  'Each bank or brokerage''s estate department',
  'Look up ''estate department'' on institution website or call main line.',
  'Some require mail-in request; allow 1-2 weeks per institution.',
  'CPA, financial advisor',
  'All statements received and filed in estate binder.',
  NULL,
  'Executor documentation plus certificate copies.',
  NULL,
  NULL,
  'Create separate folders by institution to avoid mix-ups.',
  ARRAY['e9e8956c-a06c-4370-af18-d4deec6e2f35'::uuid, 'b92ed511-6d9e-4845-927c-cdb1c6bfb795'::uuid]::uuid[],
  true,
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  '110820b5-812a-41de-832f-35e9ecafcf6d'::uuid,
  'File Deceased Spouse''s Final Income Tax Return',
  'Submit IRS Form 1040 (and state return) for the year of death, marked ''Deceased''.',
  'months-2-3'::task_phase,
  'Due on regular tax deadline (April 15) unless extension filed',
  'medium'::task_priority,
  false,
  ARRAY['Online'::contact_method, 'Mail'::contact_method],
  ARRAY['W-2s, 1099s, K-1s', 'Death certificate copy', 'Form 1310 (if refund due to estate)'],
  'Settles IRS obligations; refunds go to estate, not individual.',
  'Use ''Married Filing Jointly'' for the year of death to capture higher deductions.',
  'CPA or enrolled agent',
  'IRS Directory of Preparers or referrals.',
  'Standard tax-prep process; check ''Deceased'' box on top of Form 1040.',
  'CPA, enrolled agent',
  'IRS transcript shows return accepted and any refund issued.',
  NULL,
  NULL,
  NULL,
  NULL,
  'If refund is due, file Form 1310 to claim it on behalf of the estate.',
  ARRAY['caaaf141-fc72-4539-a5d8-9b2bd1d825e7'::uuid]::uuid[],
  false,
  'caaaf141-fc72-4539-a5d8-9b2bd1d825e7'::uuid,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  'a068ffc6-34f9-4d63-b2ef-7c2e0050c9f8'::uuid,
  'Obtain Real Estate Appraisals for Date-of-Death Value',
  'Hire a licensed appraiser to set the fair-market value of real property as of the date of death.',
  'months-2-3'::task_phase,
  'Within 90 days',
  'medium'::task_priority,
  true,
  ARRAY['Phone'::contact_method, 'Email'::contact_method, 'In-Person'::contact_method],
  ARRAY['Property address', 'Access for appraisal inspection'],
  'Establishes new cost basis, reducing capital-gains tax when property is sold.',
  'Request a retrospective appraisal—must state value ''as of'' the exact death date.',
  'State-licensed residential or commercial appraiser',
  'Local Realtor® referrals or Appraisal Institute directory.',
  'Appraiser visits property, delivers report in 7-10 days.',
  'Real-estate attorney (if multiple heirs)',
  'PDF appraisal report showing appraised value as of date of death.',
  NULL,
  'Provide access to property; sign engagement letter.',
  NULL,
  NULL,
  'Order two originals—court may require a certified copy.',
  ARRAY['e9e8956c-a06c-4370-af18-d4deec6e2f35'::uuid]::uuid[],
  true,
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  'e9e8956c-a06c-4370-af18-d4deec6e2f35'::uuid,
  'Contact Financial Advisor to Adjust Accounts and Cost Basis',
  'Meet with fiduciary advisor to re-title assets, adjust cost basis, and set new withdrawal plans.',
  'months-2-3'::task_phase,
  'Within 90 days',
  'high'::task_priority,
  false,
  ARRAY['In-Person'::contact_method, 'Phone'::contact_method, 'Email'::contact_method],
  ARRAY['Certified death certificate', 'Date-of-death statements', 'Appraisal reports'],
  'Ensures investments continue smoothly and tax basis is recorded before market changes.',
  'Ask advisor to run a 12-month cash-flow projection reflecting new income sources.',
  'Certified Financial Planner™ or fiduciary advisor',
  'NAPFA or CFP Board search tools.',
  'Paperwork for beneficiary transfers, cost-basis letters, updated income withdrawals.',
  'CFP®, CPA',
  'All inherited accounts retitled; cost basis documented; cash-flow plan updated.',
  NULL,
  NULL,
  NULL,
  NULL,
  'Keep a separate ''inherited assets'' account—simplifies future tax tracking.',
  ARRAY['caaaf141-fc72-4539-a5d8-9b2bd1d825e7'::uuid, 'a068ffc6-34f9-4d63-b2ef-7c2e0050c9f8'::uuid]::uuid[],
  false,
  'caaaf141-fc72-4539-a5d8-9b2bd1d825e7'::uuid,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  'c47e4b7a-8072-4c1f-8817-f727c3c0d51e'::uuid,
  'Notify Key Financial Institutions and Credit Bureaus',
  'Inform banks, mortgage lender, DMV, health insurer, and credit bureaus of the death and freeze credit.',
  'first-month'::task_phase,
  'Within 30 days',
  'high'::task_priority,
  true,
  ARRAY['Phone'::contact_method, 'Mail'::contact_method, 'Online'::contact_method],
  ARRAY['Death certificate (certified copy)', 'Account numbers', 'Executor authority documents (if applicable)'],
  'Prevents fraud, stops unwanted mail, and transitions joint accounts correctly.',
  'Ask the credit bureaus to place a ''deceased alert''—this blocks most identity-theft attempts.',
  'Experian, Equifax, TransUnion; each bank/lender; DMV deaths unit; health insurer',
  'Official websites; use addresses provided for estate notifications.',
  'Letters or upload portals; bureaus send confirmation within 10 days.',
  NULL,
  'All institutions mark account as deceased or transferred; credit report shows freeze.',
  NULL,
  'Executor letters and certificate copies.',
  NULL,
  NULL,
  'Close unused joint credit cards last—some mortgage scores rely on card age.',
  ARRAY['28d2819d-25e0-4d80-9b1f-074d2888e2ec'::uuid]::uuid[],
  false,
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  'a6e27328-57f6-4a8e-97e8-a62c48e8ed6c'::uuid,
  'Secure and Retitle Property (Vehicles, Real Estate, Valuable Assets)',
  'Lock up standalone assets titled solely in deceased''s name and retitle per court order or trust.',
  'months-2-3'::task_phase,
  'Within 90 days',
  'medium'::task_priority,
  true,
  ARRAY['In-Person'::contact_method, 'Mail'::contact_method, 'Online'::contact_method],
  ARRAY['Letters testamentary or trust certificate', 'Death certificate', 'Original vehicle title or deed'],
  'Prevents loss, liability, and unauthorized use while estate is settled.',
  'Photograph the odometer and property condition before storage—protects against disputes.',
  'DMV title office, county recorder, storage facility',
  'State DMV website, county recorder office address.',
  'Title transfer forms, recording fees, possible probate court approval.',
  'Real-estate attorney, estate lawyer',
  'New title/deed lists correct owner (estate or beneficiary) and asset is safely stored or insured.',
  NULL,
  'Executor/trustee authorization papers.',
  NULL,
  NULL,
  'Keep estate assets insured until sold or transferred—lapses void claims.',
  ARRAY['4dce1e1f-16f1-4049-9047-14a8e52f1bb0'::uuid]::uuid[],
  false,
  '4dce1e1f-16f1-4049-9047-14a8e52f1bb0'::uuid,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

INSERT INTO task_templates (
  id, name, description, phase, timeframe, priority, can_delegate,
  contact_methods, required_documents, why_it_matters, human_insight,
  who_to_contact, how_to_find_contact, what_to_expect, suggested_professionals,
  what_success_looks_like, suggested_quantity, delegation_requirements,
  resources, downloadable_guides, pro_tips, related_task_ids,
  unlocks_other_steps, depends_on_task_id, created_at, updated_at
)
VALUES (
  '1c01c877-b0d9-4fba-8efa-4fb83ca4bad4'::uuid,
  'Check State Controller''s Unclaimed Property Website',
  'Search for and claim any funds or property owed to the deceased that have escheated to the state.',
  'months-3-6'::task_phase,
  'Within 6 months',
  'low'::task_priority,
  true,
  ARRAY['Online'::contact_method, 'Mail'::contact_method],
  ARRAY['Death certificate', 'Proof of executor authority', 'Claim form'],
  'Recovers forgotten bank accounts, stock dividends, or refunds that increase estate value.',
  'Search yearly—new items are added every summer.',
  'State controller or treasury unclaimed-property division',
  'Google ''(State) unclaimed property'' (official .gov site).',
  'Submit claim online or by mail; processing 60-180 days.',
  NULL,
  'Check or security certificates issued to the estate/beneficiary.',
  NULL,
  'Executor documents plus certificate.',
  NULL,
  NULL,
  'Ignore third-party finders who charge a fee—claiming yourself is free.',
  NULL,
  false,
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

-- Insert task steps

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  'Call the funeral director to confirm they can file the request',
  1,
  'Call the funeral director to confirm they can file the request',
  'action'::step_type,
  '{"contactMethod":"phone","phoneScript":"Hi, this is [Your Name]. My [relationship] passed away on [date], and I need to request certified death certificates. Can you help me file this request, or should I contact the vital records office directly? I''ll need about 10-15 copies.","documentsNeeded":["Date of death","Full name of deceased","Your relationship to deceased"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  'If NOT using funeral director: download your county''s death-certificate application form.',
  2,
  'If NOT using funeral director: download your county''s death-certificate application form.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  'Complete the form; specify number of certified copies (10-15).',
  3,
  'Complete the form; specify number of certified copies (10-15).',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  'Gather required proof (ID, relationship).',
  4,
  'Gather required proof (ID, relationship).',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  'Submit form and payment online or in person at vital-records office.',
  5,
  'Submit form and payment online or in person at vital-records office.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  'Track shipment or pick up in person once ready.',
  6,
  'Track shipment or pick up in person once ready.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '4b2f8000-9e33-46f5-8ae7-673c94796df0'::uuid,
  'File copies in a secure folder; note how many remain after each use.',
  7,
  'File copies in a secure folder; note how many remain after each use.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '574e2267-6f4c-4cf9-a1e7-6612e77797c1'::uuid,
  'List all essential bills: mortgage/rent, utilities, phones, insurance.',
  1,
  'List all essential bills: mortgage/rent, utilities, phones, insurance.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '574e2267-6f4c-4cf9-a1e7-6612e77797c1'::uuid,
  'Contact each provider to pay outstanding balances and set up auto-pay',
  2,
  'Contact each provider to pay outstanding balances and set up auto-pay',
  'action'::step_type,
  '{"contactMethod":"phone","phoneScript":"Hello, I''m calling about account [ACCOUNT NUMBER]. I need to pay any outstanding balance and set up automatic payments. Can you help me with the current balance and set up auto-pay from my bank account?","documentsNeeded":["Account numbers","Bank account or credit card for auto-pay setup"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '574e2267-6f4c-4cf9-a1e7-6612e77797c1'::uuid,
  'Pay any outstanding balances immediately.',
  3,
  'Pay any outstanding balances immediately.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '574e2267-6f4c-4cf9-a1e7-6612e77797c1'::uuid,
  'Turn on auto-pay for at least two billing cycles.',
  4,
  'Turn on auto-pay for at least two billing cycles.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '574e2267-6f4c-4cf9-a1e7-6612e77797c1'::uuid,
  'Document confirmation numbers and next-due dates.',
  5,
  'Document confirmation numbers and next-due dates.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '574e2267-6f4c-4cf9-a1e7-6612e77797c1'::uuid,
  'Share an up-to-date status list with any helpers.',
  6,
  'Share an up-to-date status list with any helpers.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '2706d589-2d28-4f1e-9ea4-d937bddab3a9'::uuid,
  'Download last 3 months of bank/credit-card statements.',
  1,
  'Download last 3 months of bank/credit-card statements.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '2706d589-2d28-4f1e-9ea4-d937bddab3a9'::uuid,
  'Highlight charges <$20 or labeled as subscriptions.',
  2,
  'Highlight charges <$20 or labeled as subscriptions.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '2706d589-2d28-4f1e-9ea4-d937bddab3a9'::uuid,
  'Log in or call each service to cancel auto-renew',
  3,
  'Log in or call each service to cancel auto-renew',
  'action'::step_type,
  '{"contactMethod":"phone","phoneScript":"Hello, I need to cancel my subscription/membership effective immediately. The account is under [DECEASED NAME] who passed away on [date]. Can you help me cancel this and confirm there will be no further charges?","documentsNeeded":["Account number or email address","Date of death"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '2706d589-2d28-4f1e-9ea4-d937bddab3a9'::uuid,
  'Screenshot or save each cancellation confirmation.',
  4,
  'Screenshot or save each cancellation confirmation.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '2706d589-2d28-4f1e-9ea4-d937bddab3a9'::uuid,
  'Set calendar reminder to verify no further charges next cycle.',
  5,
  'Set calendar reminder to verify no further charges next cycle.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'dd5a79f0-459e-4507-a95e-1d1581e6809f'::uuid,
  'Make a list of every institution that has an emergency-contact form.',
  1,
  'Make a list of every institution that has an emergency-contact form.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'dd5a79f0-459e-4507-a95e-1d1581e6809f'::uuid,
  'Print or download their change request forms.',
  2,
  'Print or download their change request forms.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'dd5a79f0-459e-4507-a95e-1d1581e6809f'::uuid,
  'Complete forms with new contact details and sign.',
  3,
  'Complete forms with new contact details and sign.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'dd5a79f0-459e-4507-a95e-1d1581e6809f'::uuid,
  'Submit forms and notify institutions of the change',
  4,
  'Submit forms and notify institutions of the change',
  'action'::step_type,
  '{"contactMethod":"email","emailTemplate":"Subject: Emergency Contact Update - [YOUR NAME]\\n\\nDear [Institution Name],\\n\\nI am writing to update my emergency contact information in your records. My previous emergency contact, [DECEASED NAME], passed away on [DATE].\\n\\nPlease update my emergency contact to:\\nName: [NEW CONTACT NAME]\\nRelationship: [RELATIONSHIP]\\nPhone: [PHONE NUMBER]\\nEmail: [EMAIL ADDRESS]\\n\\nI have attached the completed emergency contact form for your records.\\n\\nPlease confirm this change has been processed.\\n\\nThank you,\\n[YOUR NAME]\\n[YOUR CONTACT INFO]","documentsNeeded":["Completed emergency contact form","New contact''s information"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'dd5a79f0-459e-4507-a95e-1d1581e6809f'::uuid,
  'Confirm changes were processed by checking portals or calling back.',
  5,
  'Confirm changes were processed by checking portals or calling back.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '28d2819d-25e0-4d80-9b1f-074d2888e2ec'::uuid,
  'Make a full list of tech and utility providers (use past 3 months of bills).',
  1,
  'Make a full list of tech and utility providers (use past 3 months of bills).',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '28d2819d-25e0-4d80-9b1f-074d2888e2ec'::uuid,
  'Call each provider to transfer or cancel service',
  2,
  'Call each provider to transfer or cancel service',
  'action'::step_type,
  '{"contactMethod":"phone","phoneScript":"Hello, I need to update the account holder information for account #[ACCOUNT NUMBER]. The primary account holder, [DECEASED NAME], passed away on [DATE]. I need to either transfer the account to my name or cancel the service. What is your process for this?","documentsNeeded":["Account number","Death certificate (certified copy)","Your ID for verification"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '28d2819d-25e0-4d80-9b1f-074d2888e2ec'::uuid,
  'Repeat for electricity, water, trash, and security devices.',
  3,
  'Repeat for electricity, water, trash, and security devices.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '28d2819d-25e0-4d80-9b1f-074d2888e2ec'::uuid,
  'Log in to streaming services and update payment info or cancel.',
  4,
  'Log in to streaming services and update payment info or cancel.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '28d2819d-25e0-4d80-9b1f-074d2888e2ec'::uuid,
  'For password managers or crypto wallets, follow provider''s deceased-user procedure for transfer or recovery.',
  5,
  'For password managers or crypto wallets, follow provider''s deceased-user procedure for transfer or recovery.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '28d2819d-25e0-4d80-9b1f-074d2888e2ec'::uuid,
  'Record confirmation numbers and effective transfer dates.',
  6,
  'Record confirmation numbers and effective transfer dates.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '34379d19-9e35-446c-88bb-686f23389dd3'::uuid,
  'Call Social Security Administration to schedule appointment',
  1,
  'Call Social Security Administration to schedule appointment',
  'action'::step_type,
  '{"contactMethod":"phone","phoneScript":"Hello, I need to schedule an appointment to report a death and apply for survivor benefits. My [relationship] passed away on [date], and I need to apply for survivor benefits for myself and my children. Their Social Security number was [SSN]. What is the earliest appointment available at my local office?","documentsNeeded":["Deceased''s Social Security number","Your Social Security number","List of dependent children and their SSNs"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '34379d19-9e35-446c-88bb-686f23389dd3'::uuid,
  'Provide deceased''s SSN and survivors'' details to the agent.',
  2,
  'Provide deceased''s SSN and survivors'' details to the agent.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '34379d19-9e35-446c-88bb-686f23389dd3'::uuid,
  'Request earliest available in-office appointment.',
  3,
  'Request earliest available in-office appointment.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '34379d19-9e35-446c-88bb-686f23389dd3'::uuid,
  'Write down date, time, and the documents they require.',
  4,
  'Write down date, time, and the documents they require.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '34379d19-9e35-446c-88bb-686f23389dd3'::uuid,
  'Arrange transportation and child care if needed.',
  5,
  'Arrange transportation and child care if needed.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '34379d19-9e35-446c-88bb-686f23389dd3'::uuid,
  'Set a reminder 24 hours before the appointment.',
  6,
  'Set a reminder 24 hours before the appointment.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '9abac705-d2d1-4489-bbea-1ba2cf7b0528'::uuid,
  'Locate the policy and confirm you are named beneficiary.',
  1,
  'Locate the policy and confirm you are named beneficiary.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '9abac705-d2d1-4489-bbea-1ba2cf7b0528'::uuid,
  'Call the claims department to initiate your claim',
  2,
  'Call the claims department to initiate your claim',
  'action'::step_type,
  '{"contactMethod":"phone","phoneScript":"Hello, I need to file a life insurance claim. The policyholder, [DECEASED NAME], passed away on [DATE]. I am the named beneficiary on policy number [POLICY NUMBER]. Can you please start the claims process and tell me what documents I need to submit?","documentsNeeded":["Policy number","Your relationship to deceased","Preliminary cause of death if known"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '9abac705-d2d1-4489-bbea-1ba2cf7b0528'::uuid,
  'Complete claim form; attach certified death certificate.',
  3,
  'Complete claim form; attach certified death certificate.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '9abac705-d2d1-4489-bbea-1ba2cf7b0528'::uuid,
  'Submit via insurer''s portal or certified mail.',
  4,
  'Submit via insurer''s portal or certified mail.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '9abac705-d2d1-4489-bbea-1ba2cf7b0528'::uuid,
  'Track claim status weekly until payout arrives.',
  5,
  'Track claim status weekly until payout arrives.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '0cd648d6-864f-4b97-b5fc-e9c14d085059'::uuid,
  'Contact HR department to report the death',
  1,
  'Contact HR department to report the death',
  'action'::step_type,
  '{"contactMethod":"phone","phoneScript":"Hello, I''m calling to report that [DECEASED NAME], employee ID [ID NUMBER], passed away on [DATE]. I need to discuss final paycheck, benefits, and any company life insurance policies. Can you walk me through what needs to be done and what documents you''ll need from me?","documentsNeeded":["Employee ID or last pay stub","Death certificate (certified copy)","Your relationship to deceased"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '0cd648d6-864f-4b97-b5fc-e9c14d085059'::uuid,
  'Request details on final paycheck and unused PTO payout.',
  2,
  'Request details on final paycheck and unused PTO payout.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '0cd648d6-864f-4b97-b5fc-e9c14d085059'::uuid,
  'Ask for a list of company-provided benefits (life, 401k, pension).',
  3,
  'Ask for a list of company-provided benefits (life, 401k, pension).',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '0cd648d6-864f-4b97-b5fc-e9c14d085059'::uuid,
  'Provide death certificate copy and complete any forms.',
  4,
  'Provide death certificate copy and complete any forms.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '0cd648d6-864f-4b97-b5fc-e9c14d085059'::uuid,
  'Track expected payment dates and benefit terminations.',
  5,
  'Track expected payment dates and benefit terminations.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'c64b4ac9-ca2e-4e0d-88ec-4da5b33d1dc9'::uuid,
  'Arrive at SSA office 15 minutes early with all documents.',
  1,
  'Arrive at SSA office 15 minutes early with all documents.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'c64b4ac9-ca2e-4e0d-88ec-4da5b33d1dc9'::uuid,
  'Take a ticket; wait to be called.',
  2,
  'Take a ticket; wait to be called.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'c64b4ac9-ca2e-4e0d-88ec-4da5b33d1dc9'::uuid,
  'Meet with Social Security representative',
  3,
  'Meet with Social Security representative',
  'action'::step_type,
  '{"contactMethod":"in-person","inPersonTalking":["State clearly: ''I''m here to report a death and apply for survivor benefits''","Provide the deceased''s full name, Social Security number, and date of death","Explain your relationship to the deceased and current living situation","Ask specifically about survivor benefits, dependent benefits, and any lump-sum death payment","Request a written summary of all benefits you''re eligible for and when they start","Ask when you can expect the first payment and how it will be delivered"],"documentsNeeded":["Death certificate (certified copy)","Marriage certificate","Birth certificates for children","Photo IDs for all applicants"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'c64b4ac9-ca2e-4e0d-88ec-4da5b33d1dc9'::uuid,
  'Receive printed summary of benefits and start dates.',
  4,
  'Receive printed summary of benefits and start dates.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'c64b4ac9-ca2e-4e0d-88ec-4da5b33d1dc9'::uuid,
  'Verify accuracy before leaving.',
  5,
  'Verify accuracy before leaving.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'f12d0c64-9c3e-44c3-9b3e-51e5b2f4e7b1'::uuid,
  'List every active policy and note renewal dates.',
  1,
  'List every active policy and note renewal dates.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'f12d0c64-9c3e-44c3-9b3e-51e5b2f4e7b1'::uuid,
  'Call each insurer to report the death and update policies',
  2,
  'Call each insurer to report the death and update policies',
  'action'::step_type,
  '{"contactMethod":"phone","phoneScript":"Hello, I''m calling to report that my [spouse/parent] who was on our policy has passed away. I need to remove them from the policy and update the billing information. The policy number is [NUMBER]. Can you help me with this process and let me know what documents you''ll need?","documentsNeeded":["Policy number","Death certificate (certified copy)","Your driver''s license or ID"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'f12d0c64-9c3e-44c3-9b3e-51e5b2f4e7b1'::uuid,
  'Submit required documentation to insurance company',
  3,
  'Submit required documentation to insurance company',
  'action'::step_type,
  '{"contactMethod":"email","emailTemplate":"Subject: Policy Update - Death Notification for [DECEASED NAME]\\n\\nDear [Insurance Company],\\n\\nI am writing to notify you of the death of [DECEASED NAME], who was a policyholder/covered person on policy #[POLICY NUMBER].\\n\\nPlease remove [DECEASED NAME] from the policy effective [DATE OF DEATH] and update the policy to reflect [NEW PRIMARY INSURED NAME] as the primary policyholder.\\n\\nI have attached a certified copy of the death certificate. Please confirm the changes and send me an updated declarations page showing the new premium amount.\\n\\nIf you need any additional documentation, please let me know.\\n\\nThank you for your assistance.\\n\\nSincerely,\\n[YOUR NAME]\\n[PHONE NUMBER]","documentsNeeded":["Certified death certificate (attached)","Copy of current policy"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'f12d0c64-9c3e-44c3-9b3e-51e5b2f4e7b1'::uuid,
  'Ask for new rate or refund confirmation in writing.',
  4,
  'Ask for new rate or refund confirmation in writing.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'f12d0c64-9c3e-44c3-9b3e-51e5b2f4e7b1'::uuid,
  'File updated declarations pages in your estate folder.',
  5,
  'File updated declarations pages in your estate folder.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'd8800e24-2fb7-46e6-9df0-d99162da7a8d'::uuid,
  'Call plan administrator to request beneficiary claim forms',
  1,
  'Call plan administrator to request beneficiary claim forms',
  'action'::step_type,
  '{"contactMethod":"phone","phoneScript":"Hello, I''m calling regarding the 401(k) plan for [DECEASED NAME] who passed away on [DATE]. I am the named beneficiary and need to start the claim process. Can you send me the beneficiary claim packet and explain my options for receiving the funds?","documentsNeeded":["Deceased''s Social Security number","Plan account number if available","Your relationship to deceased"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'd8800e24-2fb7-46e6-9df0-d99162da7a8d'::uuid,
  'Choose rollover vs. lump-sum with your advisor/CPA.',
  2,
  'Choose rollover vs. lump-sum with your advisor/CPA.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'd8800e24-2fb7-46e6-9df0-d99162da7a8d'::uuid,
  'Complete and notarize forms; attach death certificate.',
  3,
  'Complete and notarize forms; attach death certificate.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'd8800e24-2fb7-46e6-9df0-d99162da7a8d'::uuid,
  'Mail via certified mail; keep tracking.',
  4,
  'Mail via certified mail; keep tracking.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'd8800e24-2fb7-46e6-9df0-d99162da7a8d'::uuid,
  'Confirm receipt and transfer; save final statement.',
  5,
  'Confirm receipt and transfer; save final statement.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '0ffe71e3-6354-4967-8879-09786e41cde3'::uuid,
  'Locate pension contact info on latest statement.',
  1,
  'Locate pension contact info on latest statement.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '0ffe71e3-6354-4967-8879-09786e41cde3'::uuid,
  'Call pension administrator to request survivor claim kit',
  2,
  'Call pension administrator to request survivor claim kit',
  'action'::step_type,
  '{"contactMethod":"phone","phoneScript":"Hello, I''m calling about the pension plan for [DECEASED NAME] who passed away on [DATE]. I believe there may be survivor benefits available. Can you please send me the survivor claim forms and explain what benefits I might be eligible for?","documentsNeeded":["Deceased''s Social Security number","Marriage certificate (if applicable)","Pension plan number if available"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '0ffe71e3-6354-4967-8879-09786e41cde3'::uuid,
  'Complete forms; select payout option.',
  3,
  'Complete forms; select payout option.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '0ffe71e3-6354-4967-8879-09786e41cde3'::uuid,
  'Attach required documents; mail certified.',
  4,
  'Attach required documents; mail certified.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '0ffe71e3-6354-4967-8879-09786e41cde3'::uuid,
  'Call to verify processing and first payment date.',
  5,
  'Call to verify processing and first payment date.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '323b80d8-3fbe-4c3b-a765-795a2b7b823e'::uuid,
  'Book appointment with estate attorney.',
  1,
  'Book appointment with estate attorney.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '323b80d8-3fbe-4c3b-a765-795a2b7b823e'::uuid,
  'Provide original will and death certificate.',
  2,
  'Provide original will and death certificate.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '323b80d8-3fbe-4c3b-a765-795a2b7b823e'::uuid,
  'Review asset list; confirm beneficiaries.',
  3,
  'Review asset list; confirm beneficiaries.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '323b80d8-3fbe-4c3b-a765-795a2b7b823e'::uuid,
  'Attorney files will with probate court (if needed).',
  4,
  'Attorney files will with probate court (if needed).',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '323b80d8-3fbe-4c3b-a765-795a2b7b823e'::uuid,
  'Sign updated powers of attorney, trusts, or deeds as advised.',
  5,
  'Sign updated powers of attorney, trusts, or deeds as advised.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '4dce1e1f-16f1-4049-9047-14a8e52f1bb0'::uuid,
  'Meet attorney to decide trust vs. probate path.',
  1,
  'Meet attorney to decide trust vs. probate path.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '4dce1e1f-16f1-4049-9047-14a8e52f1bb0'::uuid,
  'File initial petition and pay court fees (probate) OR sign trustee acceptance (trust).',
  2,
  'File initial petition and pay court fees (probate) OR sign trustee acceptance (trust).',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '4dce1e1f-16f1-4049-9047-14a8e52f1bb0'::uuid,
  'Publish notice to creditors as required.',
  3,
  'Publish notice to creditors as required.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '4dce1e1f-16f1-4049-9047-14a8e52f1bb0'::uuid,
  'Inventory assets and file with court/trust beneficiaries.',
  4,
  'Inventory assets and file with court/trust beneficiaries.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '4dce1e1f-16f1-4049-9047-14a8e52f1bb0'::uuid,
  'Distribute assets per court order or trust terms.',
  5,
  'Distribute assets per court order or trust terms.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'b92ed511-6d9e-4845-927c-cdb1c6bfb795'::uuid,
  'Engage CPA; deliver asset valuations and statements.',
  1,
  'Engage CPA; deliver asset valuations and statements.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'b92ed511-6d9e-4845-927c-cdb1c6bfb795'::uuid,
  'Review draft Form 706 schedules A-O.',
  2,
  'Review draft Form 706 schedules A-O.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'b92ed511-6d9e-4845-927c-cdb1c6bfb795'::uuid,
  'Sign and date final return.',
  3,
  'Sign and date final return.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'b92ed511-6d9e-4845-927c-cdb1c6bfb795'::uuid,
  'Mail return via certified mail with tracking.',
  4,
  'Mail return via certified mail with tracking.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'b92ed511-6d9e-4845-927c-cdb1c6bfb795'::uuid,
  'Save stamped copy and proof of delivery.',
  5,
  'Save stamped copy and proof of delivery.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'caaaf141-fc72-4539-a5d8-9b2bd1d825e7'::uuid,
  'List every financial institution from prior statements.',
  1,
  'List every financial institution from prior statements.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'caaaf141-fc72-4539-a5d8-9b2bd1d825e7'::uuid,
  'Call each estate department to request date-of-death statements',
  2,
  'Call each estate department to request date-of-death statements',
  'action'::step_type,
  '{"contactMethod":"phone","phoneScript":"Hello, I''m the executor for the estate of [DECEASED NAME] who passed away on [DATE]. I need to request date-of-death account statements for all accounts held with your institution. What is your process for this and what documentation do you need?","documentsNeeded":["Letters testamentary or trust certificate","Death certificate (certified copy)","List of known account numbers"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'caaaf141-fc72-4539-a5d8-9b2bd1d825e7'::uuid,
  'Submit formal written request to financial institutions',
  3,
  'Submit formal written request to financial institutions',
  'action'::step_type,
  '{"contactMethod":"mail","emailTemplate":"Subject: Request for Date-of-Death Account Statements - Estate of [DECEASED NAME]\\n\\nDear Estate Department,\\n\\nI am writing to request date-of-death account statements for all accounts held by [DECEASED NAME] (SSN: XXX-XX-XXXX) who passed away on [DATE OF DEATH].\\n\\nAs the court-appointed executor/trustee, I need these statements for estate administration and tax purposes. Please provide statements showing account balances and holdings as of [DATE OF DEATH] for:\\n\\n- All checking and savings accounts\\n- Investment/brokerage accounts\\n- Retirement accounts (401k, IRA, etc.)\\n- Any other accounts or services\\n\\nEnclosed please find:\\n- Certified copy of death certificate\\n- Copy of Letters Testamentary/Trust Certificate\\n- Copy of my identification\\n\\nPlease mail the statements to the address below or advise if you have a secure electronic delivery option.\\n\\nThank you for your assistance.\\n\\nSincerely,\\n[YOUR NAME], Executor/Trustee\\n[MAILING ADDRESS]\\n[PHONE NUMBER]","documentsNeeded":["Executor documentation","Certified death certificate copy","Your photo ID copy"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'caaaf141-fc72-4539-a5d8-9b2bd1d825e7'::uuid,
  'Send requests; track receipt dates.',
  4,
  'Send requests; track receipt dates.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'caaaf141-fc72-4539-a5d8-9b2bd1d825e7'::uuid,
  'Upload PDFs to secure cloud and label clearly.',
  5,
  'Upload PDFs to secure cloud and label clearly.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '110820b5-812a-41de-832f-35e9ecafcf6d'::uuid,
  'Gather all income documents (W-2s, 1099s, etc.).',
  1,
  'Gather all income documents (W-2s, 1099s, etc.).',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '110820b5-812a-41de-832f-35e9ecafcf6d'::uuid,
  'Deliver to CPA along with death certificate copy.',
  2,
  'Deliver to CPA along with death certificate copy.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '110820b5-812a-41de-832f-35e9ecafcf6d'::uuid,
  'Review draft return, ensure ''Deceased'' noted beside name.',
  3,
  'Review draft return, ensure ''Deceased'' noted beside name.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '110820b5-812a-41de-832f-35e9ecafcf6d'::uuid,
  'Sign and e-file or mail with tracking.',
  4,
  'Sign and e-file or mail with tracking.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '110820b5-812a-41de-832f-35e9ecafcf6d'::uuid,
  'Save acceptance notice and refund confirmation.',
  5,
  'Save acceptance notice and refund confirmation.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'a068ffc6-34f9-4d63-b2ef-7c2e0050c9f8'::uuid,
  'Contact appraisers for quotes and availability',
  1,
  'Contact appraisers for quotes and availability',
  'action'::step_type,
  '{"contactMethod":"phone","phoneScript":"Hello, I need a retrospective real estate appraisal for estate purposes. The property owner passed away on [DATE] and I need the property valued as of that specific date. The property is located at [ADDRESS]. What would you charge for this type of appraisal and when could you complete it?","documentsNeeded":["Property address","Date of death","Your authority as executor/trustee"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'a068ffc6-34f9-4d63-b2ef-7c2e0050c9f8'::uuid,
  'Select appraiser; sign engagement letter.',
  2,
  'Select appraiser; sign engagement letter.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'a068ffc6-34f9-4d63-b2ef-7c2e0050c9f8'::uuid,
  'Provide property access or lockbox code.',
  3,
  'Provide property access or lockbox code.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'a068ffc6-34f9-4d63-b2ef-7c2e0050c9f8'::uuid,
  'Receive draft report; confirm correct effective date.',
  4,
  'Receive draft report; confirm correct effective date.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'a068ffc6-34f9-4d63-b2ef-7c2e0050c9f8'::uuid,
  'Pay invoice and save final PDF in estate files.',
  5,
  'Pay invoice and save final PDF in estate files.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'e9e8956c-a06c-4370-af18-d4deec6e2f35'::uuid,
  'Email advisor to schedule a comprehensive estate review meeting',
  1,
  'Email advisor to schedule a comprehensive estate review meeting',
  'action'::step_type,
  '{"contactMethod":"email","emailTemplate":"Subject: Urgent - Estate Review Meeting Needed for [DECEASED NAME]\\n\\nDear [ADVISOR NAME],\\n\\n[DECEASED NAME] passed away on [DATE] and I need to schedule a meeting to review and retitle all inherited accounts and assets.\\n\\nI need help with:\\n- Retitling inherited investment accounts\\n- Updating cost basis for all assets\\n- Reviewing and adjusting withdrawal/income strategies\\n- Understanding tax implications of inherited assets\\n\\nI have the following documents ready:\\n- Date-of-death account statements\\n- Real estate appraisals\\n- Death certificate\\n- Letters testamentary/trust documents\\n\\nWhat is your earliest availability for a comprehensive review? I prefer to meet in person if possible.\\n\\nThank you,\\n[YOUR NAME]\\n[PHONE NUMBER]","documentsNeeded":["Date-of-death statements","Real estate appraisals","Death certificate","Executor/trustee documentation"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'e9e8956c-a06c-4370-af18-d4deec6e2f35'::uuid,
  'Provide DoD statements and appraisals in advance.',
  2,
  'Provide DoD statements and appraisals in advance.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'e9e8956c-a06c-4370-af18-d4deec6e2f35'::uuid,
  'Sign transfer paperwork for each inherited account.',
  3,
  'Sign transfer paperwork for each inherited account.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'e9e8956c-a06c-4370-af18-d4deec6e2f35'::uuid,
  'Review cost-basis adjustment letter and keep copy.',
  4,
  'Review cost-basis adjustment letter and keep copy.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'e9e8956c-a06c-4370-af18-d4deec6e2f35'::uuid,
  'Set new automatic withdrawals or reinvestment strategy.',
  5,
  'Set new automatic withdrawals or reinvestment strategy.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'c47e4b7a-8072-4c1f-8817-f727c3c0d51e'::uuid,
  'Create standardized notification letter with deceased information',
  1,
  'Create standardized notification letter with deceased information',
  'action'::step_type,
  '{"contactMethod":"mail","emailTemplate":"Subject: Death Notification - Please Update Records for [DECEASED NAME]\\n\\nDear [Institution Name],\\n\\nI am writing to notify you of the death of [DECEASED NAME] (SSN: XXX-XX-XXXX) who passed away on [DATE OF DEATH].\\n\\nPlease update your records to reflect this death and take the following actions:\\n- Mark all accounts as deceased\\n- Freeze any individual credit lines or accounts\\n- Stop all marketing communications\\n- Convert joint accounts to individual accounts for the surviving account holder\\n\\nI am attaching a certified copy of the death certificate for your records.\\n\\nFor accounts requiring additional documentation, please contact me at [PHONE NUMBER] or [EMAIL ADDRESS].\\n\\nThank you for your prompt attention to this matter.\\n\\nSincerely,\\n[YOUR NAME]\\n[RELATIONSHIP TO DECEASED]\\n[CONTACT INFORMATION]","documentsNeeded":["Certified death certificate copy","Account numbers if available","Your identification"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'c47e4b7a-8072-4c1f-8817-f727c3c0d51e'::uuid,
  'Send or upload to each credit bureau requesting freeze and alert.',
  2,
  'Send or upload to each credit bureau requesting freeze and alert.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'c47e4b7a-8072-4c1f-8817-f727c3c0d51e'::uuid,
  'Call each bank to report death and ask for estate department',
  3,
  'Call each bank to report death and ask for estate department',
  'action'::step_type,
  '{"contactMethod":"phone","phoneScript":"Hello, I''m calling to report the death of an account holder, [DECEASED NAME], who passed away on [DATE]. I need to report this death and understand the process for handling their accounts. Can you transfer me to your estate department or tell me what steps I need to take?","documentsNeeded":["Deceased''s full name and SSN","Account numbers if known","Your relationship to deceased"]}'::jsonb,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'c47e4b7a-8072-4c1f-8817-f727c3c0d51e'::uuid,
  'Mail death certificate copies where required.',
  4,
  'Mail death certificate copies where required.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'c47e4b7a-8072-4c1f-8817-f727c3c0d51e'::uuid,
  'Verify updates by pulling free credit reports after 30 days.',
  5,
  'Verify updates by pulling free credit reports after 30 days.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'a6e27328-57f6-4a8e-97e8-a62c48e8ed6c'::uuid,
  'Inventory all solely-titled assets (vehicles, real property, collectibles).',
  1,
  'Inventory all solely-titled assets (vehicles, real property, collectibles).',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'a6e27328-57f6-4a8e-97e8-a62c48e8ed6c'::uuid,
  'Arrange secure storage or change locks as needed.',
  2,
  'Arrange secure storage or change locks as needed.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'a6e27328-57f6-4a8e-97e8-a62c48e8ed6c'::uuid,
  'Complete DMV or recorder title-transfer forms with legal authority.',
  3,
  'Complete DMV or recorder title-transfer forms with legal authority.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'a6e27328-57f6-4a8e-97e8-a62c48e8ed6c'::uuid,
  'Submit forms, pay fees, and obtain new title/deed.',
  4,
  'Submit forms, pay fees, and obtain new title/deed.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  'a6e27328-57f6-4a8e-97e8-a62c48e8ed6c'::uuid,
  'Update insurance policies to new titled owner.',
  5,
  'Update insurance policies to new titled owner.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '1c01c877-b0d9-4fba-8efa-4fb83ca4bad4'::uuid,
  'Visit the official unclaimed-property site for each state where the deceased lived.',
  1,
  'Visit the official unclaimed-property site for each state where the deceased lived.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '1c01c877-b0d9-4fba-8efa-4fb83ca4bad4'::uuid,
  'Enter name and previous addresses.',
  2,
  'Enter name and previous addresses.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '1c01c877-b0d9-4fba-8efa-4fb83ca4bad4'::uuid,
  'If matches appear, click ''Claim'' and complete online form.',
  3,
  'If matches appear, click ''Claim'' and complete online form.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '1c01c877-b0d9-4fba-8efa-4fb83ca4bad4'::uuid,
  'Upload required documents or mail as instructed.',
  4,
  'Upload required documents or mail as instructed.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);
INSERT INTO task_steps (task_template_id, title, "order", instructions, step_type, communication_helpers, created_at, updated_at)
VALUES (
  '1c01c877-b0d9-4fba-8efa-4fb83ca4bad4'::uuid,
  'Track claim status and deposit any recovered funds into the estate account.',
  5,
  'Track claim status and deposit any recovered funds into the estate account.',
  'instruction'::step_type,
  NULL,
  NOW(),
  NOW()
);

